const {StyleSheet} = require('react-native');
const {COLORS} = require('../../../assets/constants/global_colors');
const {WD, mS, hS} = require('../../../utils/metrics');
const {
  PoppinsMedium,
  PoppinsSemiBold,
  PoppinsRegular,
  Outfit,
  Urbanist,
  UrbanistMedium,
  OutfitRegular,
  OutfitLight,
} = require('../../../assets/constants/global_fonts');
import {Shadow5} from '../../../utils/helpers';

export const UserLoginScreenStyles = StyleSheet.create({
  safe: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
  },
  loginContainer: {
    paddingVertical: 65,
    paddingHorizontal: 30,
    backgroundColor: COLORS.WHITE,
    flex: 3,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  logoContainer: {
    paddingVertical: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scroll: {
    paddingTop: '12.5%',
    paddingTop: '5%',
  },
  headingTxt: {
    lineHeight: 27.72,
    fontSize: hS(24),
    marginBottom: 20,
    color: COLORS.PrimaryColor,
    fontFamily: 'Outfit-Regular',
  },
  phoneCodeText: {
    // fontSize: mS(20),
    // color: COLORS.DARK,
    // fontFamily: PoppinsSemiBold,
    // textAlign: "center",
    // marginVertical: hS(8),
    fontSize: mS(18),
    color: '#000',
    // fontFamily: PoppinsSemiBold,
    marginVertical: hS(8),
    paddingVertical: 5,
    marginHorizontal: hS(16),
  },
  loginSubText: {
    fontFamily: 'Outfit-Regular',
    fontSize: hS(16),
    color: COLORS.SecondaryFontColor,
  },

  signUpViewText: {
    fontSize: 18,
    fontWeight: '500',
    //paddingLeft:20,
    paddingVertical: 5,
    color: '#1B1B1B',
    marginHorizontal: hS(16),
  },
  phoneBox: {
    backgroundColor: COLORS.fieldColor,
    width: '100%',
    height: 60,
    borderColor: COLORS.fieldBorderColor,
    borderWidth: 1.5,
    borderRadius: 8,
  },
  CheckBoxViews: {
    backgroundColor: 'transparent',
    width: WD - hS(16) * 2,
    height: mS(100),
    //alignSelf: "center",
    // paddingHorizontal: hS(8),
    // marginHorizontal: hS(16),
    // borderWidth: mS(2),
    // //borderColor: COLORS.DARK,
    // borderColor:'#F1F2F7',
    // borderRadius: mS(8),
    //  justifyContent:'start'
  },
  CheckboxText: {
    fontSize: mS(18), // Adjust font size
    color: '#898989', // Use your preferred color
    fontFamily: 'Outfit', // Use your preferred font
    padding: 15,
    // justifyContent:'start',
    paddingHorizontal: hS(8),
  },
  phoneBoxIP: {
    height: mS(56),
    fontSize: mS(18),
    // color: COLORS.DARK,
    color: '#000',
    fontFamily: PoppinsMedium,
    paddingHorizontal: hS(8),
  },
  sendOTPBox: {
    backgroundColor: COLORS.PRIMARY,
    width: hS(150),
    height: hS(50),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hS(16),
    marginBottom: hS(16),
    borderRadius: mS(8),
  },
  sendOTPBoxTxt: {
    fontSize: mS(18),
    color: COLORS.WHITE,
    fontFamily: PoppinsMedium,
  },
  pwdBox: {
    width: mS(54),
    height: mS(54),
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomaskTxt1: {
    fontSize: mS(18),
    color: '#898989',
    fontFamily: 'Outfit-Light',
    textAlign: 'center',
  },
  bottomaskTxt2: {
    color: '#097E52',
    fontFamily: 'Outfit-Medium',
    fontSize: mS(18),
    lineHeight: 22.68,
  },

  otpContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  otpBottom: {
    backgroundColor: '#fff',
    marginHorizontal: 0,
    marginTop: 'auto',
    borderTopLeftRadius: mS(6),
    borderTopRightRadius: mS(6),
  },
  otpCloseBtn: {
    backgroundColor: 'rgba(0,0,0,0.05)',
    width: hS(30),
    height: hS(30),
    alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: hS(10),
    marginHorizontal: hS(8),
    borderRadius: hS(30),
  },
  otpHeadingTxt: {
    fontSize: mS(18),
    color: COLORS.BLACK,
    fontFamily: PoppinsMedium,
    textAlign: 'center',
  },
  otpResendTxt: {
    fontSize: mS(12),
    color: COLORS.BLACK,
    fontFamily: PoppinsRegular,
    textAlign: 'center',
    marginBottom: hS(10),
  },
  //   loginBox: {
  //     backgroundColor: COLORS.PRIMARY,
  //     width: mS(150),
  //     height: mS(50),
  //     alignSelf: "center",
  //     alignItems: "center",
  //     justifyContent: "center",
  //     marginBottom: hS(20),
  //     borderRadius: mS(8),
  //   },
  //   loginTxt: {
  //     fontSize: mS(18),
  //     color: COLORS.WHITE,
  //     fontFamily: PoppinsMedium,
  //   },

  /*New */
  loginBox: {
    backgroundColor: COLORS.buttonColor,
    width: '100%',
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
  },
  loginButtonBox: {
    backgroundColor: COLORS.buttonColor,
    width: mS(300),
    height: mS(50),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hS(20),
    borderRadius: mS(8),
    paddingTop: 15,
  },
  loginTxt: {
    fontSize: mS(16),
    color: COLORS.WHITE,
    fontFamily: UrbanistMedium,
    lineHeight: 19.2,
  },

  lineContainer: {
    marginTop: '8%',
    marginBottom: '8%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 15,
    width: '100%',
  },
  line: {
    height: 1,
    backgroundColor: '#D7D7D7',
    width: '10%',
  },
  lineText: {
    color: '#898989',
    fontFamily: 'Outfit-Light',
    fontSize: mS(18),
    lineHeight: 22.68,
  },
  phoneNumberContainer: {
    alignItems: 'flex-start',
    // marginBottom: 12,
    paddingLeft: 20,
    paddingTop: 30,
  },
  phoneInputContainer: {
    width: '100%',
    height: 60,
    backgroundColor: COLORS.fieldColor,
    borderWidth: 1.5,
    borderColor: COLORS.fieldBorderColor,
    borderRadius: 14,
  },
  phoneInputTextContainer: {
    fontFamily: 'Outfit-Regular',
    paddingVertical: 0,
  },
  dropdown: {
    width: '100%',
    height: 50,
    borderColor: '#F1F2F7',
    borderWidth: 1,
    borderRadius: 8,
    // paddingHorizontal: 8,
    backgroundColor: '#F9F9F6',
  },
  selectedValue: {
    marginTop: 16,
    fontSize: 18,
    paddingLeft: 2,
  },
});
